[package]
name = "sidevm_deployer"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"
description = "This is a demo describes how to write a pink driver contract"

[dependencies]
ink = { version = "4", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

pink-extension = { version = "0.4", default-features = false, path = "../../pink/pink-extension", features = ["ink-as-dependency"] }
system = { version = "1.0", default-features = false, path = "../system", features = ["ink-as-dependency"] }
this-crate = { path = "../../this-crate" }

[dev-dependencies]
insta = "1.32"
tracing-subscriber = "0.3"
pink-extension-runtime = { version = "0.4", default-features = false, path = "../../pink/pink-extension-runtime" }

[lib]
name = "sidevm_deployer"
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "pink-extension/std",
    "system/std",
]
ink-as-dependency = []
