name: Build release

on:
  [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-core:
    name: Build core
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: ./.github/actions/build-core
  build-pruntime:
    name: Build pruntime
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: ./.github/actions/build-pruntime
  publish:
    needs: [ build-core, build-pruntime ]
    name: Pack and publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG_NAME }}
          prerelease: true
          body: Nighty build
          files: |
            ./dist/pruntime
            ./dist/phala-node
            ./dist/pherry
            ./e2e/res/system.contract
            ./e2e/res/log_server.contract
            ./e2e/res/sidevm_deployer.contract
            ./e2e/res/tokenomic.contract